apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: system-manager
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kubernetes.docker.internal
    http:
      paths:
      - path: /api/questions
        pathType: Prefix
        backend:
          service:
            name: questions
            port: 
              number: 3000
      - path: /jwt
        pathType: Prefix
        backend:
          service:
            name: jwt-test
            port: 
              number: 3000