apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: text
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: text
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: questions
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: questions
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: match
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: match
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75